#!/usr/bin/php
<?php
$nginx_conf = '/etc/nginx/';
$websites_root = '/srv/www/';
$domain = empty($argv[1]) ? null : $argv[1];
$subdomain = empty($argv[2]) ? null : $argv[2];

// Check if domain was set
if (empty($domain)) {
    exit('No domain was set!');
}

// Check if vHost is simple domain
if (empty($subdomain)) {
    $website_root = $websites_root . $domain . '/public_html/';
    $template_name = $domain;
} else {
    $website_root = $websites_root . $domain . '/subdomains/' . $subdomain . '/public_html';
    $template_name = $subdomain . '.' . $domain;
}


// Remove symbolic link
exec('nginx_dissite ' . $template_name . '.conf');
// Reload NGINX server
exec('service nginx reload');

exec('rm -rf ' . dirname($website_root));
@unlink($nginx_conf . 'sites-available/' . $template_name . '.conf');

